from src.controllers.activity_controller import activity
from src.controllers.auth_controller import auth
from src.controllers.file_controller import fileRoute
from src.controllers.issue_controller import issue
from src.controllers.label_controller import label
from src.controllers.project_controller import project
from src.controllers.resource_controller import resource
from src.controllers.user_controller import user
from src.controllers.workspace_controller import workspace
